version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HF_API_KEY=${HF_API_KEY}
    restart: unless-stopped
